Repository hummingbird-jp/stat-web, pull requests merged in 2021-09, with the labels that each got.

#74 fix(feedback-button): add a feedback button right-bottom of the screen
  public/icons/flag_black_24dp.svg
  public/index.html
  public/styles.css
Labels: enhancement, priority: gold

#79 feat(Firestore): Firestore data structure integrated. Any user name will do.
  public/agenda.js
  public/bgm.js
  public/firebase/init.js
  public/index.js
  public/timer.js
  public/voice-visualizer.js
Labels: enhancement, priority: gold

#84 fix(stop button): show icon on timer stop button
  public/index.html
Labels: bug, priority: bronze

#89 Fix 82
  public/firebase/init.js
  public/firebase/user-info.js
  public/index.html
  public/voice-visualizer.js
Labels: bug, priority: bronze

#91 Fix 90
  public/index.js
Labels: bug

#92 発言量を表示するバーを復活！色を統一しました。
  public/index.html
  public/index.js
  public/voice-visualizer.js
Labels: ui/ux

#96 fix(link to github): users now can go directly to readme.md
  public/index.html
Labels: ui/ux, priority: gold

#98 input周りのusabilityを高めた
  public/index.html
  public/index.js
Labels: ui/ux

#101 fix(user left): talk bar updates when user left.
  public/firebase/user-info.js
  public/index.js
  public/voice-visualizer.js
Labels: bug

#103 Change icon: mic on/off -> block
  public/icons/block_black_24dp.svg
  public/index.html
  public/index.js
Labels: ui/ux

#106 README.mdに使い方を追加した！
  README.md
Labels: ui/ux, priority: gold

#107 feat(user rename): Now user can rename own user name
  public/firebase/user-info.js
  public/styles.css
Labels: ui/ux, priority: silver

#109 Readme update
  README.md
Labels: documentation, priority: gold

#114 うなずきを検出して表示できるようになった！
  public/firebase/user-info.js
  public/index.html
  public/index.js
  public/reaction.js
  public/styles.css
Labels: enhancement, priority: bronze

#116 fix(timer and bgm): disable buttons for 1s when user pressed
  public/bgm.js
  public/timer.js
Labels: ui/ux

#118 Close #117 BlazeFaceのモデルが正しく読み込まれない
  public/index.html
Labels: bug, priority: gold

#111 fix(broken layout): fix broken layout on large screen
  public/icons/share_black_24dp.svg
  public/index.html
  public/index.js
  public/styles.css
Labels: ui/ux, priority: silver

#120 Unpublish中は諸々いじれないようにした
  public/index.html
  public/index.js
  public/styles.css
Labels: enhancement, ui/ux, priority: silver

#128 Add progress bar!
  dist/index.html
Labels: enhancement, priority: silver

#135 fix(bgm): BGM will be played when users join
  src/modules/bgm.js
  src/styles.css
Labels: bug, priority: silver

#136 docs(update README.md): nodding feature section and "upcomings" section
  README.md
Labels: documentation, priority: silver

#160 chore(bgm rights): copyright text added below the bgm selector
  dist/index.html
Labels: priority: gold

#163 feat(clap): clap icon appears when user pressed "c"
  dist/index.html
  src/index.js
  src/modules/reaction.js
Labels: enhancement, priority: silver

#170 Get-url-dynamically
  dist/index.html
  src/index.js
Labels: enhancement, priority: silver
